swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile:
    get:
      description: Recupération des informations de l'utilisateur connecté (transactions , nom, etc.)
       parameters:
        - utilisateur connecté grâce au token
      responses:
        '200':
          description: Informations utilisateur récupérés avec succès
          '400':
          description: Token / Informations utilisateur invalide
        '500':
          description: Erreur serveur
  /user/profile/:compteID:
    get:
      description: Recupération de l'identifiant unique du compte sélectionné
       parameters:
        - compteID = identifiant unique du compte
      responses:
        '200':
          description: Informations du tableau des transactions récupérés avec succès
          '400':
          description: Informations du compte inexistante
        '500':
          description: Erreur serveur
  /user/profile/:compteID/:transactionID:
    get:
      description: Recupération de l'identifiant unique de la transaction du compte sélectionné
       parameters:
        - compteID = identifiant unique du compte
        - transactionID = identifiant unique de la transaction
      responses:
        '200':
          description: Informations de la transaction récupérés
          '400':
          description: Informations de la transaction inexistante
        '500':
          description: Erreur serveur
  /user/profile/:compteID/:transactionID:
    put:
      description: Ajouter une information sur la transaction sélectionnée
       parameters:
        - compteID = identifiant unique du compte
        - transactionID = identifiant unique de la transaction
      responses:
        '200':
          description: Ajout effectué avec succès
          '400':
          description: Erreur lors de l'ajout
        '500':
          description: Erreur serveur
  /user/profile/:compteID/:transactionID:
    update:
      description: Modifier une information sur la transaction sélectionnée
       parameters:
        - compteID = identifiant unique du compte
        - transactionID = identifiant unique de la transaction
      responses:
        '200':
          description: Modification effectuée avec succès
          '400':
          description: Erreur lors de la modification
        '500':
          description: Erreur serveur
  /user/profile/:compteID/:transactionID:
    delete:
      description: Supprimer une information sur la transaction sélectionnée
       parameters:
        - compteID = identifiant unique du compte
        - transactionID = identifiant unique de la transaction
      responses:
        '200':
          description: Suppression effectuée avec succès
          '400':
          description: Erreur lors de la supression
        '500':
          description: Erreur serveur

 