swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile:
    get:
      description: Récupération des informations de l'utilisateur connecté (transactions, nom, etc.)
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
      responses:
        "200":
          description: Informations utilisateur récupérées avec succès
        "400":
          description: Token / Informations utilisateur invalide
        "500":
          description: Erreur serveur
  /user/profile/{compteID}:
    get:
      description: Récupération de l'identifiant unique du compte sélectionné
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
      responses:
        "200":
          description: Informations du tableau des transactions récupérées avec succès
        "400":
          description: Informations du compte inexistantes
        "500":
          description: Erreur serveur
  /user/profile/{compteID}/{transactionID}:
    get:
      description: Récupération de l'identifiant unique de la transaction du compte sélectionné
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
      responses:
        "200":
          description: Informations de la transaction récupérées
        "400":
          description: Informations de la transaction inexistantes
        "500":
          description: Erreur serveur
    post:
      description: Ajouter une information sur la transaction sélectionnée
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Informations de la transaction à ajouter
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Ajout effectué avec succès
        "400":
          description: Erreur lors de l'ajout
        "500":
          description: Erreur serveur
    put:
      description: Modifier une information sur la transaction sélectionnée
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Informations de la transaction à modifier
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Modification effectuée avec succès
        "400":
          description: Erreur lors de la modification
        "500":
          description: Erreur serveur
    delete:
      description: Supprimer une information sur la transaction sélectionnée
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
      responses:
        "200":
          description: Suppression effectuée avec succès
        "400":
          description: Erreur lors de la suppression
        "500":
          description: Erreur serveur
