swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Récupérer les comptes pour les afficher
  /user/account/:
    get:
      description: Récupération du ou des comptes de l'utilisateur connecté
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
      responses:
        "200":
          description: Informations du ou des comptes récupérées avec succès
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 123
                    name:
                      type: string
                      example: "Compte principal"
                    transaction:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: virement
                          date:
                            type: string
                            example: 20-02-20
        "401":
          description: Token et/ou informations compte invalide
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Non autorisé"
              message:
                type: string
                example: "Token invalide ou manquant."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"

  # Récupérer les informations d'un compte
  /user/account/{accountID}:
    get:
      description: Récupération de l'identifiant unique du compte sélectionné
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
      responses:
        "200":
          description: Informations du compte récupérées avec succès
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 123
                    name:
                      type: string
                      example: "Compte principal"
                    transaction:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: virement
                          date:
                            type: string
                            example: 20-02-20
                          amount:
                            type: string
                            example: 200
                          category:
                            type: string
                            example: virement
                          note:
                            type: string
                            example: ""
                          transaction-type:
                            type: string
                            example: virement

        "404":
          description: Informations du compte inexistantes
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Problème de récupération des données"
              message:
                type: string
                example: "Aucune information n'a été trouvée"
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
  # Récupérer les informations d'une transaction pour les afficher
  /user/account/{accountID}/{transactionID}:
    get:
      description: Récupération de l'identifiant unique de la transaction du compte sélectionné et des informations de la transaction
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
      responses:
        "200":
          description: Informations du ou des comptes récupérées avec succès
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 123
                    name:
                      type: string
                      example: "Compte principal"
                    transaction:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: virement
                          date:
                            type: string
                            example: 20-02-20
        "404":
          description: Informations de la transaction inexistantes
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides"
              message:
                type: string
                example: "Requête mal formée ou données invalides."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
  # Ajouter une note sur une transaction
  /user/account/{accountID}/{transactionID}/note:
    post:
      description: Ajouter une note sur la transaction sélectionnée
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Contenu de la note ajoutée par l'utilisateur
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Ajout de la note effectué avec succès
          schema:
            type: object
            properties:
              note:
                type: string
                example: "virement a monsieur X pour achat de xxx"
        "400":
          description: Erreur lors de l'ajout
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides ou mal structurées"
              message:
                type: string
                example: "Erreur lors de l'ajout de la note."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
    # Modifier une note d'une transaction
    put:
      description: Modifier la note sur la transaction sélectionnée
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Informations de la nouvelle note
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Modification de la note effectuée avec succès
          schema:
            type: object
            properties:
              note:
                type: string
                example: "nouvelle note"
        "404":
          description: Erreur lors de la modification
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides ou mal structurées"
              message:
                type: string
                example: "Erreur lors de la modification de la note."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
    #Supprimer une note
    delete:
      description: Supprimer la note sur la transaction sélectionnée
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Supression de la note
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
      responses:
        "200":
          description: Supression de la note effectuée avec succès
          schema:
            type: object
            properties:
              note:
                type: string
                example: ""
        "404":
          description: Erreur lors de la suppression
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Impossible de supprimer la note"
              message:
                type: string
                example: "Erreur lors de la suppression de la note."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
  /user/account/{accountID}/{transactionID}/categorie:
    #Ajouter une catégorie
    post:
      description: Ajouter une catégorie sur la transaction sélectionnée
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: nouvelle catéorie ajoutée par l'utilisateur
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Ajout de la catégorie effectué avec succès
          schema:
            type: object
            properties:
              note:
                type: string
                example: "nouvelle catégorie"
        "400":
          description: Erreur lors de l'ajout
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides ou mal structurées"
              message:
                type: string
                example: "Erreur lors de l'ajout de la catégorie."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
    # Modifier la catégorie de la transaction
    put:
      description: Modifier la catégorie sur la transaction sélectionnée
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
        - name: accountID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Informations de la nouvelle catégorie choisie
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Modification de la catégorie effectuée avec succès
          schema:
            type: object
            properties:
              categorie:
                type: string
                example: "nouvelle catégorie"
        "400":
          description: Erreur lors de la modification de la catégorie
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides ou mla structurées"
              message:
                type: string
                example: "Erreur lors de la modification de la catégorie"
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
