swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Récupérer les comptes pour les afficher
  /user/compte/:
    get:
      description: Récupération du ou des comptes de l'utilisateur connecté
      parameters:
        - name: token
          in: header
          description: Token d'authentification de l'utilisateur connecté
          required: true
          type: string
      responses:
        "200":
          description: Informations du ou des comptes récupérées avec succès
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 123
                    name:
                      type: string
                      example: "Compte principal"
        "401":
          description: Token et/ou informations compte invalide
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Non autorisé"
              message:
                type: string
                example: "Token invalide ou manquant."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"

  # Récupérer les informations d'un compte
  /user/compte/{compteID}:
    get:
      description: Récupération de l'identifiant unique du compte sélectionné
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
      responses:
        "200":
          description: Informations du compte récupérées avec succès
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 123
              name:
                type: string
                example: "Compte principal"
              balance:
                type: number
                format: float
                example: 1000.50

        "401":
          description: Informations du compte inexistantes
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Problème de récupération des données"
              message:
                type: string
                example: "Aucune information n'a été trouvée"
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
  # Récupérer les informations d'une transaction pour les afficher
  /user/compte/{compteID}/{transactionID}:
    get:
      description: Récupération de l'identifiant unique de la transaction du compte sélectionné et des informations de la transaction
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
      responses:
        "200":
          description: Informations de la transaction récupérées
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 789
              description:
                type: string
                example: "Achat chez XYZ"
              amount:
                type: number
                format: float
                example: 150.75
              date:
                type: string
                format: date
                example: "2024-08-01"
        "400":
          description: Informations de la transaction inexistantes
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides"
              message:
                type: string
                example: "Requête mal formée ou données invalides."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
  # Ajouter une note sur une transaction
  /user/compte/{compteID}/{transactionID}/note:
    post:
      description: Ajouter une note sur la transaction sélectionnée
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Contenu de la note ajoutée par l'utilisateur
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Ajout de la note effectué avec succès
          schema:
            type: object
            properties:
              note:
                type: string
                example: "virement a monsieur X pour achat de xxx"
        "404":
          description: Erreur lors de l'ajout
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides"
              message:
                type: string
                example: "Erreur lors de l'ajout de la note."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
    # Modifier une note d'une transaction
    put:
      description: Modifier la note sur la transaction sélectionnée
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Informations de la nouvelle note
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Modification de la note effectuée avec succès
          schema:
            type: object
            properties:
              note:
                type: string
                example: "achat personnel"
        "404":
          description: Erreur lors de la modification
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides"
              message:
                type: string
                example: "Erreur lors de la modification de la note."
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
  # Modifier une catégorie d'une transaction
  /user/compte/{compteID}/{transactionID}/categorie:
    put:
      description: Modifier la catégorie sur la transaction sélectionnée
      parameters:
        - name: compteID
          in: path
          description: Identifiant unique du compte
          required: true
          type: string
        - name: transactionID
          in: path
          description: Identifiant unique de la transaction
          required: true
          type: string
        - name: body
          in: body
          description: Informations de la nouvelle catégorie choisie
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
      responses:
        "200":
          description: Modification de la catégorie effectuée avec succès
          schema:
            type: object
            properties:
              categorie:
                type: string
                example: "virement"
        "400":
          description: Erreur lors de la modification de la catégorie
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Données invalides"
              message:
                type: string
                example: "Erreur lors de la modification de la catégorie"
        "500":
          description: Erreur serveur
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Erreur serveur interne"
              message:
                type: string
                example: "Une erreur inattendue s'est produite sur le serveur"
